# Generated by Django 4.2.2 on 2023-06-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='boleta',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cliente.cart'),
            preserve_default=False,
        ),
    ]
