# Generated by Django 4.2.2 on 2023-06-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_remove_boleta_cart_id_boleta_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
