# Generated by Django 5.0.6 on 2024-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Herramientas Electricas', max_length=50),
        ),
    ]
